- name: create directory for unarchiving server camunda
  file:
    path: ./camunda-server
    state: directory
- name: Download and unarchive camunda server
  ansible.builtin.unarchive:
    src: https://downloads.camunda.cloud/release/camunda-bpm/run/7.17/camunda-bpm-run-7.17.0.zip
    dest: ./camunda-server
    remote_src: yes
- name: Ansible update allowed-origins
  lineinfile:
    path: ./camunda-server/configuration/default.yml
    search_string: 'allowed-origins: "*"'
    line: '      allowed-origins: "http://172.17.0.3:8080"'
- name: Add allow-credentials
  lineinfile:
    path: ./camunda-server/configuration/default.yml
    line: '      allow-credentials: "true"'
    insertafter: '      allowed-origins: "http://172.17.0.3:8080"'
    state: present
# - name: Run camunda server
#   command: "./start.sh"
#   args:
#     chdir: "camunda-server"
