---
- name: Clear all
  hosts: localhost
  tasks:
    - name: Delete docker excamad
      command: docker rm -f excamad_container
    - name: Stop camunda server
      command: "ls"
      args:
        chdir: "camunda-server"
    - name: Delete server
      file:
        path: ./camunda-server
        state: absent
    - name: Delete modeler
      file:
        path: ./camunda-modeler-5.0.0-linux-x64
        state: absent
