---
- name: Install all
  hosts: localhost
  tasks:
      ###### Settings external task:
    - name: Clone a github repository external task
      git:
       repo: https://github.com/peryevd/camunda-js-task-client.git
       dest: ./camunda-js-task-client
       clone: yes
    - name: Install dependencies
      command: "npm i"
      args:
       chdir: "camunda-js-task-client"
    - name: Run external task
      command: "node server.js"
      async: 1000
      poll: 0
      args:
        chdir: "camunda-js-task-client"

      ###### Settings camunda modeler:
    - name: Download and unarchive modeler
      ansible.builtin.unarchive:
        src: https://downloads.camunda.cloud/release/camunda-modeler/5.0.0/camunda-modeler-5.0.0-linux-x64.tar.gz
        dest: ./
        remote_src: yes
    - name: Run camunda modeler
      command: "./camunda-modeler"
      async: 1000
      poll: 0
      args:
        chdir: "camunda-modeler-5.0.0-linux-x64"

      ###### Settings excamad:
    - name: Run docker excamad
      command: docker run -d -p 8088:8088 kotovdenis/excamad:latest

      ###### Settings camunda server:
    - name: create directory for unarchiving server camunda
      file:
       path: ./camunda-server
       state: directory
    - name: Download and unarchive camunda server
      ansible.builtin.unarchive:
       src: https://downloads.camunda.cloud/release/camunda-bpm/run/7.17/camunda-bpm-run-7.17.0.zip
       dest: ./camunda-server
       remote_src: yes
    - name: Ansible update allowed-origins
      lineinfile:
        path: ./camunda-server/configuration/default.yml
        search_string: 'allowed-origins: "*"'
        line: '      allowed-origins: "http://172.17.0.3:8080"' 
    - name: Add allow-credentials
      lineinfile:
        path: ./camunda-server/configuration/default.yml
        line: '      allow-credentials: "true"'
        insertafter: '      allowed-origins: "http://172.17.0.3:8080"' 
        state: present
    - name: Run camunda server
      command: "./start.sh"
      args:
       chdir: "camunda-server"
      